eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goods.urls', namespace='goods'))
]

goods/urls.py
from django.conf.urls import url, handler404
from django.contrib.auth import views as auth_views
from . import views

# редиректим все на главную
# handler404 = views.good_list

urlpatterns = [
    url(r'^$', views.good_list, name='good_list'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^good/(?P<id>\d+)/order/$', views.order, name='order'),
    url(r'^orders/$', views.order_list, name='order_list'),
    url(r'^good/new/$', views.good_new, name='good_new'),
    url(r'^good/(?P<id>\d+)/edit/$', views.good_edit, name='good_edit'),
    url(r'^good/(?P<id>\d+)/del/$', views.good_del, name='good_del'),
    url(r'^good/(?P<id>\d+)$', views.good_detail, name='good_detail')
]

goods/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Good(models.Model):
    """Модель товара"""
    name = models.CharField(max_length=50, db_index=True, verbose_name='Название продукта')
    preview_description = models.CharField(max_length=200, blank=True, verbose_name='Краткое описание')
    description = models.TextField(blank=True, verbose_name='Полное описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    active = models.BooleanField(default=True, verbose_name="Активный")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name


class Order(models.Model):
    """Модель заказов"""
    good = models.ForeignKey(Good, verbose_name='Товар')
    user = models.ForeignKey('auth.User', verbose_name='Покупатель')
    total = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Стоимость')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ['created']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

goods/forms.py
from django import forms
from .models import Good


class GoodForm(forms.ModelForm):

    class Meta:
        model = Good
        fields = ['name', 'preview_description', 'description', 'price', 'active']

goods/views.py
import sys
from django.contrib import auth
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Good, Order
from .forms import GoodForm


def good_list(request):
    """Список товаров"""
    if request.user.is_superuser:
        goods = Good.objects.all()
        title = 'Админка'
    else:
        goods = Good.objects.filter(active=True)
        title = 'Список товаров'
    return render(request, 'goods/list.html', {'goods': goods, 'title': title, 'title_list': 'Продукты'})


def good_detail(request, id):
    """Детальная страница товара"""
    good = get_object_or_404(Good, id=id)
    return render(request, 'goods/detail.html', {'good': good})


def good_new(request):
    """Новый товар"""
    if not request.user.is_superuser:
        return render(request, 'goods/error.html', {'message_error': 'Недостаточно прав для совершения операции'})

    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            try:
                good = form.save(commit=False)
                good.author = request.user
                good.created = timezone.now()
                good.save()
            except:
                return render(request, 'goods/error.html', {'message_error': sys.exc_info()[0]})
            return redirect('goods:good_detail', id=good.id)
    else:
        form = GoodForm()
        return render(request, 'goods/good_edit.html', {'form': form})
    return redirect('/')


def good_edit(request, id):
    """Редактирование товара"""
    good = get_object_or_404(Good, id=id)
    if request.method == 'POST':
        form = GoodForm(request.POST, instance=good)
        if form.is_valid():
            try:
                form.save()
            except:
                return render(request, 'goods/error.html', {'message_error': sys.exc_info()[0]})
            return redirect('goods:good_detail', id=good.id)
    else:
        form = GoodForm(instance=good)
    return render(request, 'goods/good_edit.html', {'form': form, 'good': good})


def good_del(request, id):
    """Удаление товара"""
    if not request.user.is_superuser:
        return render(request, 'goods/error.html', {'message_error': 'Недостаточно прав для совершения операции'})

    if not Good.objects.filter(id=id).exists():
        return render(request, 'goods/error.html', {'message_error': 'Не найден объект с id={0}'.format(id)})

    Good.objects.filter(id=id).delete()
    return redirect('/')


def order_list(request):
    """Список заказов"""
    orders = Order.objects.all()
    return render(request, 'goods/list.html', {'orders': orders, 'title': 'Список заказов', 'title_list': 'Заказы'})


# @login_required()
def order(request, id):
    """Сохраняет заказ"""
    if not request.user.is_authenticated():
        return render(request, 'goods/error.html', {'message_error': 'Пользователь не авторизован'})

    good = get_object_or_404(Good, id=id)
    order = Order()
    order.good = good
    order.user = request.user
    order.total = good.price

    try:
        order.save()
    except:
        return render(request, 'goods/error.html', {'message_error': sys.exc_info()[0]})

    return redirect('/')


def login(request):
    """Авторизация пользователя"""
    if ('username' not in request.POST) or ('password' not in request.POST):
        return render(request, 'goods/error.html', {'message_error': 'Не задан логин или пароль'})

    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return redirect('/')
    else:
        return render(request, 'goods/error.html', {'message_error': 'Ошибка авторизации'})


def logout(request):
    """Выход"""
    auth.logout(request)
    return redirect('/')

goods/templates/goods/detail.html
{% extends 'goods/main.html' %}

{% load static %}

{% block title %}
    {{ good.name }}
{% endblock %}

{% block content %}

    <h1>Детальная</h1>
    <div class="container">
        <form method="post" action="{% url 'goods:order' id=good.id %}">
            {% csrf_token %}
            <div class="product-detail card">
                <h3 class="product-detail__title">{{ good.name }}</h3>

                <dl>
                    <dt>Краткое описание:</dt>
                    <dd>{{ good.preview_description }}</dd>
                    <dt>Описание:</dt>
                    <dd>{{ good.description }}</dd>
                </dl>

                <div class="product-detail__price price"><p class="gheymat">Цена: {{ good.price }}руб.</p></div>
                <input type="submit" value="Купить"/>
            </div>

        </form>
    </div>

{% endblock %}

goods/templates/goods/error.html
{% extends 'goods/main.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
{% if message_error %}
    <h1 style="color: red">{{ message_error }}</h1>
{% endif %}
{% endblock %}

goods/templates/goods/good_edit.html
{% extends 'goods/main.html' %}
{% load static %}

{% block title %}
    Новый продукт
{% endblock %}

{% block content %}
    <h1>Новый продукт</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="save btn btn-default">Сохранить</button>

        {% if good %}
            <a href="{% url 'goods:good_del' id=good.id %}" class="btn btn-danger">Удалить</a>
        {% endif %}

        <a href="/" class="btn btn-default">Отменить</a>

    </form>
{% endblock %}

goods/templates/goods/list.html
{% extends 'goods/main.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div id="main" class="product_list">
        <h2>{{ title_list }}:</h2>
        <hr size="30">

        <div class="masonry">
            {% if goods %}
                {% for good in goods %}
                    <div class="item">
                        <ul class="list-unstyled">

                            {% if user.is_superuser %}
                                <li>
                                    <a href="{% url 'goods:good_edit' id=good.id %}">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </li>

                            {% endif %}

                            <li><img src="http://placehold.it/350x350&text={{ good.name }}"></li>
                            <li>{{ good.preview_description }}</li>
                            <li><strong>Цена: {{ good.price }}руб.</strong></li>
                            <li><a href="{% url 'goods:good_detail' id=good.id %}">Подробнее »</a></li>
                        </ul>
                    </div>
                {% empty %}
                    <p>Нет товаров</p>
                {% endfor %}

            {% endif %}
        </div>

        {% if orders and user.is_superuser %}

            {% for order in orders %}
                <p>
                    <ul class="list-unstyled">
                        <li><h3>{{ order }}</h3></li>
                        <li>Товар: {{ order.good }}</li>
                        <li>Клиент: {{ order.user }}</li>
                        <li>Сумма: {{ order.total }} </li>
                    </ul>
                </p>

            {% empty %}
                <p>Нет заказов</p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

goods/templates/goods/main.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container-fluid">

    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="{% static "img/logo.png" %}">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-2">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Продукты</a></li>
                    {% if user.is_superuser %}
                        <li><a href="{% url 'goods:order_list' %}">Заказы</a></li>
                        <li><a href="/admin/">Администрирование</a></li>
                        <li><a class="btn btn-primary" href="{% url 'goods:good_new' %}" role="button">Добавить
                            продукт</a></li>
                        <li><a href="{% url 'goods:logout' %}">Выйти</a></li>
                    {% else %}
                        {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'goods:logout' %}"><strong>{{ user.username }}</strong></a>
                            </li>
                        {% else %}
                            <li>
                                <a class="btn btn-default btn-outline btn-circle collapsed" data-toggle="collapse"
                                   href="#nav-collapse2" aria-expanded="false" aria-controls="nav-collapse2">Войти</a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
                {% if not user.is_superuser %}
                    {% if not user.is_authenticated %}
                        <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse2">
                            <form class="navbar-form navbar-right form-inline" role="form"
                                  action="{% url 'goods:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="sr-only" for="Login">Имя пользователя</label>
                                    <input type="text" name="username" class="form-control" id="Login"
                                           placeholder="Login" autofocus
                                           required/>
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="Password">Пароль</label>
                                    <input type="password" name="password" class="form-control" id="Password"
                                           placeholder="Password"
                                           required/>
                                </div>
                                {#                                <button type="submit" class="btn btn-success">Войти</button>#}
                                <input type="submit" class="btn btn-success" value="Войти">
                            </form>
                        </div>
                    {% endif %}
                {% endif %}
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

</div>

<section id="content row" class="container">
    {% block content %}{% endblock %}
</section>

</body>

<link rel="stylesheet" href="{% static "css/style.css" %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

{# <script src="{% static "js/script.js" %}"></script> #}
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>